###############################################
### Batch File Processor Configuration File ###
###############################################

# Input directory relative to the system user directory
inputDir: data/in

# Output directory relative to the system user directory
outputDir: data/out

# Source file extension
inputFileExtension: .dat

# Target file extension
outputFileExtension: .done.dat

# The amount of time in seconds to wait between checks of the input directory
poolingIntervalInSeconds: 10

